name: Deploy DynamoDB to Cloud Formation
on: 
  workflow_dispatch:
    inputs:
      stack_name:
        description: 'name of the stack'
        required: true
        default: 'DynamoDB-Demo'
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy DynamoDB to Cloud Formation
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{secrets.AWS_REGION }}

    - name: Deploy to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: '${{ github.event.inputs.stack_name }}'
        template: dynamodb.yaml
        no-fail-on-empty-changeset: "1"
        

   